services:
  postgres:
    container_name: star-wars-db
    image: postgres:11-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - ${DB_PORT:-5440}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./.volumes/postgres/:/var/lib/postgresql/data/
    networks:
      - default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s