services:
  postgres:
    container_name: star-wars-db
    image: postgres:11-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - 5440:5432
    environment:
      - POSTGRES_PASSWORD=maytheforcebewithyou
      - POSTGRES_DB=starwars
    volumes:
      - ./.volumes/postgres/:/var/lib/postgresql/data/
    networks:
      - default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ${POSTGRES_DB:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s